### ISSUE TITLE
It works on android ?

### ISSUE THREAD

**Issue by krow89** [alicorn-systems/v8-adapter#35]
Any hope to get this working on android?

**Comment by caer** [comment]
Hi @krow89 ! This tool actually works quite well on Android, and Android was one of the original use-cases for the v8-adapter. However, the upstream dependency of this project (J2V8) has recently taken a radical shift in how they're handling their build process, so I am not sure if we will be able to maintain this project effectively for much longer. 

That said, you are definitely able to use the artifacts from this project in conjunction with J2V8's Android libraries in order to use it on Android. Simply put the following in your Gradle file:

```gradle
dependencies {
    // J2V8 Adapter
    compile 'io.alicorn.v8:v8-adapter:1.59'
    
    // J2V8 Runtime
    compile 'com.eclipsesource.j2v8:j2v8:4.8.0@aar'
}
```

At the moment, I am waiting to hear if the GraalVM project will be incorporating Android support in the future, as that would probably provide a better JS-Java bridge than this project does at the present.

**Comment by krow89** [comment]
Ok, thank you very much for info

**Comment by caer** [comment]
No problem; thank you so much for your interest in the project, and feel free to open up additional issues if there are any other questions or problems you run into. 😄

**Comment by krow89** [comment]
Sure. I just now get works it with android.  I want develop a simple JS scripting system for on-device use (i know, exists others solutions but i want develop something for learn and self-satisfaction purposes :wink: )
